version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: choco install dotnet4.6.2
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: git clone circleci-flask-demo repository
          command: |
            git clone git@github.com:singleobligor/windows-legacy-app.git
            pwd;ls -latr; echo ""; ls -latr windows-legacy-app
            tar -czvf windows-legacy-app-latest.tar.gz windows-legacy-app
      - run:
          name: Build Docker image
          command: |
            current_directory=$(pwd)
            echo $current_directory
            docker build -t app:latest . -f ./Dockerfile
            docker ps
      
